name: Angular action release
on:
  push:
    tags:
      - PROD_*

permissions:
  contents: write

jobs:
  app_release:
    # needs: ["app_build", "app_calculate_hashing", "generate_timestamp"]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        name: Download angular-action-artifact
        with:
          name: angular-action-demo_calculated

      - name: Create GitHub app_Release
        id: create_release
        uses: comnoco/create-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: "自動化釋出：包含 Angular build 與 hash 檔"
          draft: false
          prerelease: false

      - name: Zip demo folder
        run: |
          zip -r angular-action-demo-${{needs.generate_timestamp.outputs.timestamp}}.zip angular-action-demo

      - name: Upload demo ZIP to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: angular-action-demo-${{ needs.generate_timestamp.outputs.timestamp }}.zip
          asset_name: angular-action-demo-${{ needs.generate_timestamp.outputs.timestamp }}.zip
          asset_content_type: application/zip

      - name: Upload JSON to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url:        ${{ steps.create_release.outputs.upload_url }}
          asset_path:        ${{ needs.generate_timestamp.outputs.timestamp }}.json
          asset_name:        ${{ needs.generate_timestamp.outputs.timestamp }}.json
          asset_content_type: application/json