name: Angular actions demo
on: push

jobs:
  cicd:
    name: angular-cicd

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: List file
        run: ls -lrta

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 6.10.0

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          
      - name: pnpm install
        run: pnpm install

