name: Angular actions demo

on: push

jobs:
  cicd:
    name: angular-cicd
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List file
        run: ls -lrta
      - uses: pnpm/action-setup@v4
        with:
          version: 6.10.0
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm test
