name: Angular actions demo
on: push

jobs:
  app_build:
    name: angular-cicd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: List file
        run: ls -lrta

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 6.10.0

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: pnpm install
        run: pnpm install

      - name: pnpm run build
        run: pnpm run build

      - name: Copy hashing tools scripts to dist
        run: |
          cp -a calculate_hashing_tools ./dist/

      - uses: actions/upload-artifact@v4
        name: Upload artifact
        with:
          name: angular-action-demo
          path: ./dist/

  app_test:
    needs: app_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        name: Download angular-action-artifact
        with:
          name: angular-action-demo

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 6.10.0

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # - name: Debug - List directories
      #   run: |
      #     echo "Current directory: $(pwd)"
      #     echo "Contents:"
      #     ls -la
      #     echo "angular-action-demo contents:"
      #     ls -la angular-action-demo/ || echo "angular-action-demo directory not found"
      #     echo "calculate_hashing_tools contents:"
      #     ls -la calculate_hashing_tools/ || echo "calculate_hashing_tools directory not found"

      # - name: Calculate hashing (with error handling)
      #   run: |
      #     cd calculate_hashing_tools
      #     echo "Installing dependencies..."
      #     pnpm install
      #     echo "Running hashing calculation..."
      #     # 移除 -s 參數以顯示錯誤訊息
      #     pnpm run start ../angular-action-demo/ > ../${{ steps.ts.outputs.value }}.json
      #     echo "Command exit code: $?"
      #     echo "Output file size: $(wc -c < ../${{ steps.ts.outputs.value }}.json)"

      # - name: Debug output file
      #   run: |
      #     echo "Checking if output file exists..."
      #     if [ -f ${{ steps.ts.outputs.value }}.json ]; then
      #       echo "File exists, size: $(wc -c < ${{ steps.ts.outputs.value }}.json)"
      #       echo "First few lines:"
      #       head -10 ${{ steps.ts.outputs.value }}.json
      #     else
      #       echo "Output file does not exist!"
      #     fi

      - name: Generate timestamp
        id: ts
        run: echo "value=$(TZ=Asia/Taipei date +%Y%m%d_%H%M%S)" >> "$GITHUB_OUTPUT"

      - name: setup hashing tools
        run: |
          cd calculate_hashing_tools
          pnpm install
          pnpm -s run start ../angular-action-demo/ > ../${{ steps.ts.outputs.value }}.json

      - name: Test
        run: |
          ls -ltra
          echo $(pwd)
          cat ${{ steps.ts.outputs.value }}.json

      - uses: actions/upload-artifact@v4
        name: Upload artifact
        with:
          name: angular-action-demo_build
          path: |
            ./angular-action-demo
            ./${{ steps.ts.outputs.value }}.json
